#!/usr/bin/env python3
"""Render every per-host gateway file from hosts.json; Python standard library only.

Outputs (under --out):
  nginx/remote-term.conf   full nginx site, one ttyd location per host
  ttyd/<id>.env            TTYD_PORT for remote-ttyd@<id>.service
  ssh_config               gateway -> host SSH entries (one key per host, pinned host keys)
  aliases                  allowlist for /usr/local/bin/remote-ttyd-ssh
  web/hosts.js             host list for the page (also kept in the repository's web/)
"""

import argparse
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "status"))
from hosts_config import HOSTNAME, HostsConfigError, load_hosts, placeholders  # noqa: E402


TEMPLATE = Path(__file__).resolve().parent / "gateway" / "nginx" / "remote-term.conf.tmpl"
CONFIG_DIR = "/etc/remote-term"
PAGE_CSP = ("default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; "
            "connect-src 'self'; frame-src 'self'; frame-ancestors 'none'; base-uri 'none'; "
            "form-action 'none'; object-src 'none'")
COMMON_HEADERS = (
    'add_header Strict-Transport-Security "max-age=31536000" always;',
    'add_header X-Content-Type-Options "nosniff" always;',
    'add_header Referrer-Policy "no-referrer" always;',
)


def indent(lines, spaces):
    return "\n".join(" " * spaces + line if line else "" for line in lines)


def ttyd_location(host):
    lines = [
        f"# {host['id']}: ttyd on loopback, reached only through the login above.",
        f"location ^~ {host['path']} {{",
        "    if ($remote_term_bad_ws_origin) {",
        "        return 403;",
        "    }",
        *("    " + header for header in COMMON_HEADERS),
        "    add_header X-Frame-Options \"SAMEORIGIN\" always;",
        "    add_header Content-Security-Policy \"frame-ancestors 'self'\" always;",
        f"    proxy_pass http://127.0.0.1:{host['ttyd_port']};",
        "    proxy_http_version 1.1;",
        "    proxy_set_header Host $host;",
        "    proxy_set_header X-Real-IP $remote_addr;",
        "    proxy_set_header X-Forwarded-For $remote_addr;",
        "    proxy_set_header X-Forwarded-Proto https;",
        "    proxy_set_header Upgrade $http_upgrade;",
        "    proxy_set_header Connection $remote_term_connection_upgrade;",
        "    proxy_read_timeout 3600s;",
        "    proxy_send_timeout 3600s;",
        "    proxy_buffering off;",
        "}",
        "",
    ]
    return indent(lines, 4)


def render_nginx(hosts, domain, template=TEMPLATE):
    text = Path(template).read_text(encoding="utf-8")
    replacements = {
        "@@TTYD_LOCATIONS@@": "\n".join(ttyd_location(host) for host in hosts),
        "@@COMMON_HEADERS@@": None,
        "@@PAGE_CSP@@": PAGE_CSP,
        "@@DOMAIN_REGEX@@": re.escape(domain),
        "@@DOMAIN@@": domain,
    }
    # Common headers are indented to match where the placeholder sits.
    text = re.sub(r"^( *)@@COMMON_HEADERS@@$",
                  lambda match: indent(COMMON_HEADERS, len(match.group(1))), text, flags=re.M)
    for key, value in replacements.items():
        if value is not None:
            text = text.replace(key, value)
    leftover = re.findall(r"@@[A-Z_]+@@", text)
    if leftover:
        raise ValueError(f"unrendered placeholders: {sorted(set(leftover))}")
    return text


def render_ssh_config(hosts, config_dir=CONFIG_DIR):
    blocks = ["# Generated by deploy/render_config.py from hosts.json. One key per host, pinned host keys."]
    for host in hosts:
        blocks.append("\n".join([
            f"Host {host['id']}",
            f"    HostName {host['ssh_host']}",
            f"    Port {host['ssh_port']}",
            f"    User {host['ssh_user']}",
            f"    HostKeyAlias {host['id']}",
            f"    IdentityFile {config_dir}/keys/{host['id']}",
        ]))
    blocks.append("\n".join([
        "Host *",
        "    BatchMode yes",
        "    PreferredAuthentications publickey",
        "    IdentitiesOnly yes",
        "    StrictHostKeyChecking yes",
        f"    UserKnownHostsFile {config_dir}/known_hosts",
        "    GlobalKnownHostsFile /dev/null",
        "    UpdateHostKeys no",
        "    ForwardAgent no",
        "    ForwardX11 no",
        "    ClearAllForwardings yes",
        "    ConnectTimeout 10",
        "    ServerAliveInterval 30",
        "    ServerAliveCountMax 3",
        "    LogLevel ERROR",
    ]))
    return "\n\n".join(blocks) + "\n"


def render_hosts_js(hosts):
    entries = [{key: host[key] for key in ("id", "name", "meta", "path")} for host in hosts]
    body = json.dumps(entries, ensure_ascii=False, indent=2)
    return ("// Generated by deploy/render_config.py from hosts.json; do not edit by hand.\n"
            f"window.REMOTE_TERM_HOSTS = {body};\n")


def render_all(hosts, domain):
    files = {
        "nginx/remote-term.conf": render_nginx(hosts, domain),
        "ssh_config": render_ssh_config(hosts),
        "aliases": "".join(host["id"] + "\n" for host in hosts),
        "web/hosts.js": render_hosts_js(hosts),
    }
    for host in hosts:
        files[f"ttyd/{host['id']}.env"] = f"TTYD_PORT={host['ttyd_port']}\n"
    return files


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--hosts", type=Path, default=Path(__file__).resolve().parents[1] / "hosts.json")
    parser.add_argument("--domain", help="public domain of the gateway, e.g. djai.djscz.com")
    parser.add_argument("--out", type=Path, help="directory to write all rendered files into")
    parser.add_argument("--allow-placeholders", action="store_true",
                        help="render even if some ssh.host values are still REPLACE_... placeholders")
    parser.add_argument("--write-web", type=Path, help="only write the page's hosts.js to this path")
    parser.add_argument("--check-web", type=Path, help="fail if this hosts.js differs from hosts.json")
    args = parser.parse_args(argv)

    try:
        hosts = load_hosts(args.hosts)
    except HostsConfigError as error:
        print(f"hosts.json invalid: {error}", file=sys.stderr)
        return 2

    if args.check_web or args.write_web:
        expected = render_hosts_js(hosts)
        if args.write_web:
            args.write_web.write_text(expected, encoding="utf-8")
        if args.check_web:
            current = args.check_web.read_text(encoding="utf-8") if args.check_web.exists() else ""
            if current != expected:
                print(f"{args.check_web} is out of date; run: deploy/render_config.py --write-web {args.check_web}",
                      file=sys.stderr)
                return 1
        return 0

    if not args.domain or not args.out:
        parser.error("--domain and --out are required to render the gateway files")
    if not HOSTNAME.match(args.domain) or "." not in args.domain:
        parser.error("--domain must be a fully qualified host name")
    pending = placeholders(hosts)
    if pending and not args.allow_placeholders:
        print("hosts.json still has placeholder addresses for: " + ", ".join(pending), file=sys.stderr)
        return 1
    for relative, content in render_all(hosts, args.domain).items():
        target = args.out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
