// Generated by deploy/render_config.py from hosts.json; do not edit by hand.
window.REMOTE_TERM_HOSTS = [
  {
    "id": "vps",
    "name": "VPS",
    "meta": "入口机",
    "path": "/vps/"
  },
  {
    "id": "fa",
    "name": "财务机",
    "meta": "fa",
    "path": "/fa/"
  },
  {
    "id": "tencent-new",
    "name": "腾讯新机",
    "meta": "gg",
    "path": "/tencent-new/"
  },
  {
    "id": "tencent-main",
    "name": "腾讯大总管",
    "meta": "Chris",
    "path": "/tencent-main/"
  },
  {
    "id": "mbp-dojoy",
    "name": "另一台 Mac",
    "meta": "局域网",
    "path": "/mbp-dojoy/"
  },
  {
    "id": "mac-local",
    "name": "本机 Mac",
    "meta": "当前电脑",
    "path": "/mac-local/"
  }
];
